### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ayekta** [stepanstipl/puppet-openfire#1]
Could you give me more information about installation and how to use this module ?

**Comment by stepanstipl** [comment]
Hi, I've just committed some updates on documentation (need to improve formatting a bit). Mainly depends what system are you on, the module is supposed to work with RHEL/CentOS family, and expect you to have openfire package  (RPM on Redhat) in you package repository.

Basic usage then is just putting `include openfire` in your manifest, if you want more options see readme for available parameters, but you would use parametrised class like below:

```
class {'::openfire':
  java_ks => '/usr/local/keys/openfire/keystore',
  java_xms => '128m',
  java_xmx => '1024m',
  version => '3.9.1-1'
}
```

Module itself can be installed by putting it, together with Puppetlabs' stdlib module to your modules directory, not on Puppet forge, but I'll try to make a release there soon.

This should start openfire and actual configuration is then done through web interface reachable on port 9090, or 9091 for https by default.

If you would be interested in some other functionality feel free to add it :) or let me know and I'll see what can be done about that, same if you have any specific installation issues.
